# time
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_SUFFIX="> "
SPACESHIP_TIME_COLOR="white"

# User
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_PREFIX=""
SPACESHIP_USER_SUFFIX=""

# Dir
SPACESHIP_DIR_PREFIX="@"
SPACESHIP_DIR_SUFFIX=" "
SPACESHIP_DIR_TRUNC_REPO=true

# Git
SPACESHIP_GIT_BRANCH_ASYNC=true
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_STATUS_SHOW=true
SPACESHIP_GIT_STATUS_COLOR="green"
